import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/* Top gradient fade: dark green/black → transparent */}
        <div
          className="fixed top-0 left-0 right-0 z-40 pointer-events-none"
          style={{
            height: '10rem',
            background: 'linear-gradient(to bottom, rgba(5, 25, 10, 0.72) 0%, rgba(5, 25, 10, 0) 90%)',
          }}
        />
        {children}
      </body>
    </html>
  );
}
